using System.Collections.Specialized;
using System.Runtime.InteropServices;

namespace AmeisenBotX.Wow548.Objects.Descriptors
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct WowUnitDescriptor548
    {
        public ulong Charm;
        public ulong Summon;
        public ulong Critter;
        public ulong CharmedBy;
        public ulong SummonedBy;
        public ulong CreatedBy;
        public ulong DemonCreator;
        public ulong Target;
        public ulong Battlepet;
        public ulong ChannelObject;
        public int ChannelSpell;
        public int SummonedByHomeRealm;
        public byte Race;
        public byte Class;
        public byte PowerType;
        public byte Gender;
        public int DisplayPower;
        public int OverrideDisplayPower;
        public int Health;
        public int Power1;
        public int Power2;
        public int Power3;
        public int Power4;
        public int Power5;
        public int MaxHealth;
        public int MaxPower1;
        public int MaxPower2;
        public int MaxPower3;
        public int MaxPower4;
        public int MaxPower5;
        public fixed float PowerRegenModifier[5];
        public fixed float PowerRegenInterruptedModifier[5];
        public int Level;
        public int EffectiveLevel;
        public int FactionTemplate;
        public fixed int VirtualItemSlotId[3];
        public BitVector32 Flags1;
        public BitVector32 Flags2;
        public int AuraState;
        public fixed int BaseAttackTime[2];
        public int RangeAttackTime;
        public float BoundingRadius;
        public float CombatReach;
        public int DisplayId;
        public int NativeDisplayId;
        public int MountDisplayId;
        public float MinDamage;
        public float MaxDamage;
        public float MinOffhandDamage;
        public float MaxOffhandDamage;
        public int AnimTier;
        public int PetNumber;
        public int PetNameTimestamp;
        public int PetExperience;
        public int PetNextLevelXp;
        public float ModCastSpeed;
        public float ModSpellHaste;
        public float ModHaste;
        public float ModRangedHaste;
        public float ModHasteRegen;
        public int CreatedBySpell;
        public BitVector32 NpcFlags;
        public int NpcEmoteState;
        public int Stat0;
        public int Stat1;
        public int Stat2;
        public int Stat3;
        public int Stat4;
        public int PosStat0;
        public int PosStat1;
        public int PosStat2;
        public int PosStat3;
        public int PosStat4;
        public int NegStat0;
        public int NegStat1;
        public int NegStat2;
        public int NegStat3;
        public int NegStat4;
        public fixed int Resistances[7];
        public fixed int ResistanceModsBuffPositive[7];
        public fixed int ResistanceModsBuffNegative[7];
        public int BaseMana;
        public int BaseHealth;
        public int ShapeshiftForm;
        public int AttackPower;
        public int AttackPowerModPos;
        public int AttackPowerModNeg;
        public float AttackPowerMultiplier;
        public int RangedAttackPower;
        public fixed short RangedAttackPowerMods[2];
        public float RangedAttackPowerMultiplier;
        public float MinRangedDamage;
        public float MaxRangedDamage;
        public fixed int PowerCostModifier[7];
        public fixed float PowerCostMultiplier[7];
        public float MaxHealthModifier;
        public float HoverHeight;
        public int MinItemLevel;
        public int MaxItemLevel;
        public int WildBattlePetLevel;
        public int BattlePetCompanionNameTimestamp;
        public int InteractSpellId;

        public static readonly int EndOffset = sizeof(WowObjectDescriptor548) + sizeof(WowUnitDescriptor548);
    }
}