using System.Collections.Specialized;
using System.Runtime.InteropServices;

namespace AmeisenBotX.Wow548.Objects.Descriptors
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct WowUnitDescriptor548
    {
        public ulong Charm;
        public ulong Summon;
        public ulong Critter;
        public ulong CharmedBy;
        public ulong SummonedBy;
        public ulong CreatedBy;
        public ulong DemonCreator;
        public ulong Target;
        public ulong BattlePetCompanionGuid;
        public ulong ChannelObject;
        public int ChannelSpell;
        public int SummonedByHomeRealm;
        public byte Race;
        public byte Class;
        public byte PowerType;
        public byte Gender;
        public int DisplayPower;
        public int OverrideDisplayPowerId;
        public int Health;
        public int Power1;
        public int Power2;
        public int Power3;
        public int Power4;
        public int Power5;
        public int MaxHealth;
        public int MaxPower1;
        public int MaxPower2;
        public int MaxPower3;
        public int MaxPower4;
        public int MaxPower5;
        public fixed int PowerRegenFlatModifier[5];
        public fixed int PowerRegenInterruptedFlatModifier[5];
        public int Level;
        public int EffectiveLevel;
        public int FactionTemplate;
        public fixed int VirtualItemId[3];
        public BitVector32 Flags1;
        public BitVector32 Flags2;
        public int AuraState;
        public ulong AttackRoundBaseTime;
        public int RangedAttackRoundBaseTime;
        public int BoundingRadius;
        public float CombatReach;
        public int DisplayId;
        public int NativeDisplayId;
        public int MountDisplayId;
        public int MinDamage;
        public int MaxDamage;
        public int MinOffHandDamage;
        public int MaxOffHandDamage;
        public int AnimTier;
        public int PetNumber;
        public int PetNameTimestamp;
        public int PetExperience;
        public int PetNextLevelExperience;
        public int ModCastingSpeed;
        public int ModSpellHaste;
        public int ModHaste;
        public int ModRangedHaste;
        public int ModHasteRegen;
        public int CreatedBySpell;
        public BitVector32 NpcFlags1;
        public BitVector32 NpcFlags2;
        public int NpcEmotestate;
        public fixed int Stats[5];
        public fixed int StatPosBuff[5];
        public fixed int StatNegBuff[5];
        public fixed int Resistances[7];
        public fixed int ResistanceBuffModsPositive[7];
        public fixed int ResistanceBuffModsNegative[7];
        public int BaseMana;
        public int BaseHealth;
        public int ShapeshiftForm;
        public int AttackPower;
        public int AttackPowerModPos;
        public int AttackPowerModNeg;
        public int AttackPowerMultiplier;
        public int RangedAttackPower;
        public int RangedAttackPowerModPos;
        public int RangedAttackPowerModNeg;
        public int RangedAttackPowerMultiplier;
        public int MinRangedDamage;
        public int MaxRangedDamage;
        public fixed int PowerCostModifier[7];
        public fixed int PowerCostMultiplier[7];
        public int MaxHealthModifier;
        public int HoverHeight;
        public int MinItemLevel;
        public int MaxItemLevel;
        public int WildBattlePetLevel;
        public int BattlePetCompanionNameTimestamp;
        public int InteractSpellId;
    }
}