using AmeisenBotX.Wow.Objects.Raw.SubStructs;
using System.Runtime.InteropServices;

namespace AmeisenBotX.Wow335a.Objects.Descriptors
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct WowPlayerDescriptor335a
    {
        public ulong DuelArbiter;
        public int Flags;
        public int GuildId;
        public int GuildRank;
        public fixed byte PlayerBytes0[4];
        public fixed byte PlayerBytes1[4];
        public fixed byte PlayerBytes2[4];
        public int DuelTeam;
        public int GuildTimestamp;
        public QuestlogEntry QuestlogEntry1;
        public QuestlogEntry QuestlogEntry2;
        public QuestlogEntry QuestlogEntry3;
        public QuestlogEntry QuestlogEntry4;
        public QuestlogEntry QuestlogEntry5;
        public QuestlogEntry QuestlogEntry6;
        public QuestlogEntry QuestlogEntry7;
        public QuestlogEntry QuestlogEntry8;
        public QuestlogEntry QuestlogEntry9;
        public QuestlogEntry QuestlogEntry10;
        public QuestlogEntry QuestlogEntry11;
        public QuestlogEntry QuestlogEntry12;
        public QuestlogEntry QuestlogEntry13;
        public QuestlogEntry QuestlogEntry14;
        public QuestlogEntry QuestlogEntry15;
        public QuestlogEntry QuestlogEntry16;
        public QuestlogEntry QuestlogEntry17;
        public QuestlogEntry QuestlogEntry18;
        public QuestlogEntry QuestlogEntry19;
        public QuestlogEntry QuestlogEntry20;
        public QuestlogEntry QuestlogEntry21;
        public QuestlogEntry QuestlogEntry22;
        public QuestlogEntry QuestlogEntry23;
        public QuestlogEntry QuestlogEntry24;
        public QuestlogEntry QuestlogEntry25;
        public VisibleItemEnchantment VisibleItemEnchantment1;
        public VisibleItemEnchantment VisibleItemEnchantment2;
        public VisibleItemEnchantment VisibleItemEnchantment3;
        public VisibleItemEnchantment VisibleItemEnchantment4;
        public VisibleItemEnchantment VisibleItemEnchantment5;
        public VisibleItemEnchantment VisibleItemEnchantment6;
        public VisibleItemEnchantment VisibleItemEnchantment7;
        public VisibleItemEnchantment VisibleItemEnchantment8;
        public VisibleItemEnchantment VisibleItemEnchantment9;
        public VisibleItemEnchantment VisibleItemEnchantment10;
        public VisibleItemEnchantment VisibleItemEnchantment11;
        public VisibleItemEnchantment VisibleItemEnchantment12;
        public VisibleItemEnchantment VisibleItemEnchantment13;
        public VisibleItemEnchantment VisibleItemEnchantment14;
        public VisibleItemEnchantment VisibleItemEnchantment15;
        public VisibleItemEnchantment VisibleItemEnchantment16;
        public VisibleItemEnchantment VisibleItemEnchantment17;
        public VisibleItemEnchantment VisibleItemEnchantment18;
        public VisibleItemEnchantment VisibleItemEnchantment19;
        public int ChosenTitle;
        public int FakeInebriation;
        public int WowPlayerPad;
        public fixed ulong InventorySlots[23];
        public fixed ulong BackpackSlots[16];
        public fixed ulong BankSlots[28];
        public fixed ulong BankBagSlots[7];
        public fixed ulong VendorBuyBackSlots[12];
        public fixed ulong KeyringSlots[32];
        public fixed ulong TokenSlots[32];
        public ulong Farsight;
        public ulong KnownTitles0;
        public ulong KnownTitles1;
        public ulong KnownTitles2;
        public ulong KnownCurrencies;
        public int Xp;
        public int NextLevelXp;
        public fixed short SkillInfos[768];
        public int CharacterPoints1;
        public int CharacterPoints2;
        public int TrackCreatures;
        public int TrackResources;
        public float BlockPercentage;
        public float DodgePercentage;
        public float ParryPercentage;
        public int Expertise;
        public int OffhandExpertise;
        public float CritPercentage;
        public float RangedCritPercentage;
        public float OffhandCritPercentage;
        public float SpellCritPercentage;
        public int ShieldBlock;
        public float ShieldBlockPercentage;
        public fixed byte ExploredZones[512];
        public int RestStateExpirience;
        public int FieldCoinage;
        public fixed int ModDamageDonePos[7];
        public fixed int ModDamageDoneNeg[7];
        public fixed int ModDamageDonePercentage[7];
        public int ModHealingDone;
        public float ModHealingPercentage;
        public float ModHealingDonePercentage;
        public int ModTargetResistance;
        public int ModTargetPhysicalResistance;
        public fixed byte PlayerBytes3[4];
        public int AmmoId;
        public int SelfResSpell;
        public int PvpMedals;
        public fixed int BuybackPrices[12];
        public fixed int BuybackTimestamps[12];
        public fixed short Kills[2];
        public int TodayContribution;
        public int YesterdayContribution;
        public int LifetimeHonorableKills;
        public fixed byte PlayerBytes4[4];
        public int WatchedFactionIndex;
        public fixed int CombatRatings[25];
        public fixed int ArenaTeamInfo[21];
        public int HonorCurrency;
        public int ArenaCurrency;
        public int MaxLevel;
        public fixed int DailyQuests[25];
        public fixed float RuneRegens[4];
        public fixed int NoReagentCosts[3];
        public fixed int GlyphSlots[6];
        public fixed int Glyphs[6];
        public int GlyphsEnabled;
        public int PetSpellPower;

        public static readonly int EndOffset = 4712;
    }
}